# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  csharpemployeecrud:
    image: csharpemployeecrud
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5255:5255

  db:
    container_name: 'employee_csharp'
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 3307:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo